repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.5
    hooks:
      - id: ruff-format
      - id: ruff
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.15.0
    hooks:
      - id: mypy
  - repo: local
    hooks:
      - id: check-coverage
        name: Check minimum coverage
        entry: python antares-python/scripts/check_coverage.py
        language: system
        types: [python]

