# ============================
# Antares Simulation Config
# ============================

[antares.simulation]
emission_interval = 20
controller_bind_addr = "0.0.0.0:17394"

# ============================
# Ships to add at startup
# ============================

[[antares.simulation.initial_ships]]
type = "line"
initial_position = [-70_000.0, -70_000.0]
angle = 0.785
speed = 20.0

[[antares.simulation.initial_ships]]
type = "circle"
initial_position = [30_000.0, -30_000.0]
radius = 20_000.0
speed = 40.0

[[antares.simulation.initial_ships]]
type = "random"
initial_position = [-20_000.0, 20_000.0]
max_speed = 30.0

[[antares.simulation.initial_ships]]
type = "stationary"
initial_position = [50_000.0, 50_000.0]

# ============================
# Antares Radar Config
# ============================

[antares.radar]
bind_addr = "0.0.0.0:17396"

[antares.radar.detector]
range = 100_000.0
speed = 0.0
angle = 0.785398
start_coordinates = [4.0, -72.0]

[antares.radar.broadcast]
type = "websocket"
