[simulation]
emission_interval = 20
controller_bind_addr = "127.0.0.1:18900"

[[simulation.initial_ships]]
initial_position = [-50.0, 50.0]
type = "line"
angle = 0.785
speed = 5.0

[[simulation.initial_ships]]
initial_position = [50.0, -50.0]
type = "circle"
radius = 20.0
speed = 5.0

[[simulation.initial_ships]]
initial_position = [-50.0, -50.0]
type = "random"
max_speed = 20.0

[[simulation.initial_ships]]
initial_position = [50.0, 50.0]
type = "stationary"

[radar]
bind_addr = "127.0.0.1:18950"

[radar.detector]
range = 100.0
speed = 0.0
angle = 0.0
start_coordinates = [4.0, -72.0]

[radar.broadcast]
type = "tcp"
