name: Deploy Docs to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    name: Build and Deploy Documentation

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'

      - name: Generate Docs with Chirpy
        uses: jsurrea/showcase-chirpy-easy-docs@v1.0.0
        with:
          docs-dir: docs

      - name: Upload site artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: theme/_site

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
