name: Publish antares-python to PyPI

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  publish:
    name: Build and Publish
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: antares-python

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install uv
        run: |
          curl -Ls https://astral.sh/uv/install.sh | bash
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Build package
        run: |
          uv venv
          source .venv/bin/activate
          uv pip install -U build
          python -m build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
          packages-dir: antares-python/dist/
